site_name: Celeste Code Mod 教程
repo_url: https://github.com/Saplonily/CelesteModTutorial
site_description: Celeste Code Mod Tutorial
site_author: Saplonily

theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/images/favicon.png
  font: false
  features:
    - content.code.copy
    - content.tabs.link

  palette: 
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

extra_css:
  - css/content.css

markdown_extensions:
  - admonition # 警告
  - meta # 元数据
  - attr_list
  - md_in_html
  - def_list # 列表
  - pymdownx.tilde # 下划线
  - pymdownx.tasklist # 列表
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight: # 语法高亮
      pygments_lang_class: true
      linenums: true

nav:
  - 首页: "index.md"
  - Mapping:
    - 首页: "Mapping/index.md"
  - Codeing:
    - 首页: "Coding/index.md"
    - 一些准备:
        - 基础环境配置: "Coding/coding_setup/basic_env.md"
        - 调试: "Coding/coding_setup/debug.md"
        - 阅读代码: "Coding/coding_setup/code_reading.md"
    - 基础:
        - Celeste, Everest, MonoMod: "Coding/basics/celeste_everest_monomod.md"
        - 更多EC: "Coding/basics/ec_common.md"
        - Flag, Tag, Tracker: "Coding/basics/flag_tag_tracker.md"
        - Session, Settings, SaveData: "Coding/basics/session_settings_savedata.md"
    - 进阶:
        - 跨 Mod 交互: "Coding/advanced/cross_mod_interactions.md"
    # - Loenn:
    #     - Loenn 目录结构: "loenn/folder_structure.md"
    #     - Loenn 基础配置: "loenn/basic_configurations.md"
    #     - Entity 结构: "loenn/entity_structs.md" 
    #     - Trigger 结构: "loenn/trigger_structs.md"
    #     - Loenn 绘制: "loenn/rendering.md"
    #     - Loenn 节点: "loenn/nodes.md"
    #     - Effect 结构: "loenn/effect_structs.md"
    - 实战:
        - 测试地图: "Coding/coding_challenges/test_map.md"
        - 简单自定义实体: "Coding/coding_challenges/simple_entity.md"
        - 简单自定义Trigger: "Coding/coding_challenges/simple_trigger.md"
        - 简单贴图: "Coding/coding_challenges/simple_texturing.md"
    - 钩子:
        - 钩子: "Coding/hooks/hook.md"
        - IL: "Coding/hooks/il.md"
        - IL 钩子与随意钩取: "Coding/hooks/adv_hooks.md"
        - 协程的钩取与私有成员访问: "Coding/hooks/adv_hooks2.md"     
    - 组件:
        - Sprite, Image: "Coding/components/sprite_image.md"
        - Alarm, Tween, Coroutine: "Coding/components/alarm_tween_coroutine.md"  
        - StateMachine: "Coding/components/statemachine.md"    
    - 额外:
        - XML:
          - XML 简单介绍: "Coding/extra/xml/xml_speedrun.md"
        - Lua:
          - 开始: "Coding/extra/lua/begin.md"
          - 基本语法: "Coding/extra/lua/syntax.md"
          - 数据类型: "Coding/extra/lua/data_type.md"
          - 流程控制: "Coding/extra/lua/control_flow.md"
          - 运算符: "Coding/extra/lua/operator.md"
          - 迭代器: "Coding/extra/lua/iterator.md"
          - 模块: "Coding/extra/lua/module.md"
          - 标准库: "Coding/extra/lua/standard_library.md"
        - LuaCutscene:
          - 开始: "Coding/extra/lua_cutscene/begin.md"
          - 参考: "Coding/extra/lua_cutscene/reference.md"
          - C# 交互: "Coding/extra/lua_cutscene/cs_access.md"
          - 例子: "Coding/extra/lua_cutscene/examples.md"
    - 历史归档:
        - 基础环境配置: "Coding/arc/basic_env.md"
        - 通过模板创建项目: "Coding/arc/project_template.md"
        - 偏好: "Coding/arc/preference.md"
        - 偏好-sdk-styled-proj: "Coding/arc/sdk-styled-proj.md"
    - 杂项:
        - ChangeLog: "Coding/misc/change_log.md"
        - ToDoList: "Coding/misc/to_do_list.md"
    #      - What: "Coding/misc/what.md"
  - CustomMusic:
    - 首页: "CustomMusic/index.md"