site_name: 蔚蓝Code Mod教程
repo_url: https://github.com/Saplonily/CelesteModTourial
site_description: Celeste Code Mod Tourial
site_author: Saplonily

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/favicon.png
  features:
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition # 警告
  - meta # 元数据
  - attr_list
  - md_in_html
  - def_list # 列表
  - pymdownx.mark # mark
  - pymdownx.tilde # 下划线
  - pymdownx.inlinehilite # 高亮
  - pymdownx.snippets # 语法高亮
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences: # 语法高亮
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist # 列表
  - pymdownx.details
  - pymdownx.highlight: # 语法高亮
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

nav:
  - 首页: "index.md"
  - 入门:
      - Celeste, Everest, MonoMod: "begin/CelesteEverestMonoMod.md"
      - 基础环境配置: "begin/BasicEnv.md"
      - 偏好: "begin/prefer.md"
      - 钩子, 阅读代码: "begin/hook,code.md"
      - 简单自定义实体: "begin/SimpleEntity.md"
      - 简单自定义Trigger: "begin/SimpleTrigger.md"
      - 阅读代码2: "begin/Reading.md"
      - 简单贴图: "begin/SimpleTexturing.md"
# - 过渡:
#     - 进阶EC: "trans/ECcommon.md"
#     - 常见Celeste, Monocle:
#       - Alarm, Tween: "trans/common/Alarm,Tween.md"
#     - Flag: "trans/Flag.md"
#     - 进阶钩子:
#         - 认识 IL: "trans/IL.md"
#         - IL 钩子与随意钩取: "trans/AdvHooks.md"
#     - 私有访问: "trans/PrivateAccess.md"
  - 历史归档:
      - 基础环境配置: "arc/BasicEnv.md"
      - 偏好-sdk-styled-proj: "arc/sdk-styled-proj.md"
  - 其他:
      - XML简单速成: "other/xml-speedrun.md"