site_name: 蔚蓝Code Mod教程
repo_url: https://github.com/Saplonily/CelesteModTourial
site_description: Celeste Code Mod Tourial
site_author: Saplonily

theme:
  name: material
  logo: assets/images/favicon.png
  features:
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition # 警告
  - meta # 元数据
  - def_list # 列表
  - pymdownx.mark # mark
  - pymdownx.tilde # 下划线
  - pymdownx.inlinehilite # 高亮
  - pymdownx.snippets # 语法高亮
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences: # 语法高亮
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist # 列表
  - pymdownx.details
  - pymdownx.highlight: # 语法高亮
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

nav:
  - 首页: "index.md"
  - 入门:
      - Celeste, Everest, MonoMod: "begin/CelesteEverestMonoMod.md"
      - 基础环境配置: "begin/BasicEnv.md"
      - 偏好: "begin/prefer.md"
      - 钩子, 阅读代码, demo1: "begin/hook,code,demo1.md"
      - 简单自定义实体: "begin/SimpleEntity.md"
      - 简单自定义Trigger: "begin/SimpleTrigger.md"
#     - 阅读代码: "begin/Reading.md"
#     - <del>更多 Loenn 设置与 EntityData</del>: "begin/AdvLoennAndData.md"
# - <del>过渡</del>:
#     - <del>进行贴图</del>: "trans/Texturing.md"
#     - <del>进阶EC</del>: "trans/ECcommon.md"
#     - <del>常见Celeste, Monocle类</del>: "trans/Common.md"
#     - <del>Flag</del>: "trans/Flag.md"
#     - <del>进阶钩子</del>:
#         - <del>认识 IL</del>: "trans/IL.md"
#         - <del>IL 钩子与随意钩取</del>: "trans/AdvHooks.md"
#     - <del>私有访问</del>: "trans/PrivateAccess.md"
  - 历史归档:
      - 基础环境配置: "arc/BasicEnv.md"
      - 偏好-sdk-styled-proj: "arc/sdk-styled-proj.md"
  - 其他:
      - XML简单速成: "other/xml-speedrun.md"


# - 入门
#   - Celeste, Everest, MonoMod
#   - 基础环境配置
#   - 自动化环境
# - 阅读/修改代码初步
#   - 阅读Celeste的代码
#   - Monocle及EC架构及部分基础知识
#   - On钩子初步
#   - 认识IL
#   - IL钩子
#   - "自由"地钩取
#   - 协程的钩取
#   - 访问私有成员
#     - 反射
#     - DynamicData / DynData
# - 游戏设置初步
#   - 添加Mod设置选项
# - 简单自定义实体
#   - 简单地图布置
#   - 简单loenn配置
#   - Logging
#   - 按键输入
#   - 使用Alarm, Tween, Coroutine等组件
# - 进阶
#   - Everest事件
#   - 继承并使用钩子
#   - 更多Monocle组件, 实体
#   - 高级设置
# - Loenn配置进阶
# ...其他想起来再写
